# Generated by Django 6.0.4 on 2026-06-08 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uni_price', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Preco unitario')),
                ('subtotal', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Subtotal')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='games.game')),
            ],
            options={
                'verbose_name': 'Item de pedido',
                'verbose_name_plural': 'Itens de pedido',
                'ordering': ['id'],
            },
        ),
    ]
