# Generated by Django 6.0.4 on 2026-06-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persons.person')),
                ('salary', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Preco unitario')),
                ('position', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Suporte',
                'verbose_name_plural': 'Suportes',
                'ordering': ['id'],
            },
            bases=('persons.person',),
        ),
    ]
