# Generated by Django 6.0.4 on 2026-06-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('description', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
