# Generated by Django 6.0.4 on 2026-06-08 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('description', '0002_alter_description_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('brand', models.TextField(max_length=50, verbose_name='Marca')),
                ('launch_date', models.DateField(verbose_name='Data Fabricacao')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço')),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='description.description')),
            ],
            options={
                'verbose_name': 'Jogo',
                'verbose_name_plural': 'Jogos',
                'ordering': ['id'],
            },
        ),
    ]
